shallow_clone: true

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

cache:
  - C:\cmake-3.6.3-win32-x86

install:
  - ps: |
      if (![IO.File]::Exists("C:\cmake-3.6.3-win32-x86\bin\cmake.exe")) {
        Start-FileDownload 'https://cmake.org/files/v3.6/cmake-3.6.3-win32-x86.zip'
        7z x -y cmake-3.6.3-win32-x86.zip -oC:\
      }
      $env:PATH="C:\cmake-3.6.3-win32-x86\bin;$env:PATH"
  - mkdir build && cd build
  - ps: |
      if ($env:PLATFORM -eq "x64" -and $env:CONFIGURATION -eq "Debug") {
        $env:HEADER_CHECK=1
      } else {
        $env:HEADER_CHECK=0
      }
  - cmake .. -DRANGE_V3_HEADER_CHECKS=%HEADER_CHECK% -DCMAKE_BUILD_TYPE=%CONFIGURATION% -T v140_clang_c2

build:
  project: c:/projects/range-v3/build/ALL_BUILD.vcxproj
  parallel: true
  verbosity: minimal

test_script:
  - ctest -j2

deploy: off
